version: '3'
services:
  web:
    image: 'nginx:latest'
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./config:/etc/nginx/conf.d
      - /Users/changchaofeng/nginx/www:/www
      - /Users/changchaofeng/developer/logs/:/var/log/nginx
  php:
    image: 'php:dev'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /Users/changchaofeng/nginx/www:/www
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - /Users/changchaofeng/developer/logs/:/var/log/php
  db:
    image: "mysql:latest"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=12345678
      - TZ=Asia/Shanghai
    ports:
      - "13306:3306"
    volumes:
      - /Users/changchaofeng/nginx/mysql/logs:/logs
      - /Users/changchaofeng/nginx/mysql/data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
  golang:
    image: "golang:dev"
    environment:
      - TZ=Asia/Shanghai
    ports: 
      - "10000:80"
    tty: true
    volumes:
      - /Users/changchaofeng/nginx/www:/go/src/app
networks:
  default:
    external:
      name: mynet
